#!/bin/bash

# Tambahkan user sementara (opsional)
if [ -w /etc/passwd ] && ! getent passwd "$(id -u)" >/dev/null; then
    echo "server:x:$(id -u):$(id -g):Server User:/home/container:/bin/bash" >> /etc/passwd
fi

# Set prompt PS1 langsung di shell ini
PS1="root@${HOST_NAME:-container}:\w\$ "

# Pindah ke home
cd /home/container || cd ~

# Jalankan shell interaktif langsung (tanpa exec bash lagi)
exec bash --noprofile --norc
